//App States
export const SAVE_CREATE_PROPERTY_DATA = 'SAVE_CREATE_PROPERTY_DATA';
export const REMOVE_CREATE_PROPERTY_DATA = 'REMOVE_CREATE_PROPERTY_DATA';

//Set Sublists
export const GET_SUBLISTS = 'GET_SUBLISTS';
export const GET_SUBLISTS_SUCCESS = 'GET_SUBLISTS_SUCCESS';

//Set Current Addres
export const SET_ADDRESS_REQUEST = 'SET_ADDRESS_REQUEST';
export const SET_ADDRESS_SUCCESS = 'SET_ADDRESS_SUCCESS';

//Create My Property
export const CREATE_MY_PROPERTY_REQUEST = 'CREATE_MY_PROPERTY_REQUEST';
export const CREATE_MY_PROPERTY_SUCCESS = 'CREATE_MY_PROPERTY_SUCCESS';
export const CREATE_MY_PROPERTY_FINALLY = 'CREATE_MY_PROPERTY_FINALLY';

//Get My Properties
export const GET_MY_PROPERTIES_REQUEST = 'GET_MY_PROPERTIES_REQUEST';
export const GET_MY_PROPERTIES_SUCCESS = 'GET_MY_PROPERTIES_SUCCESS';
export const GET_MY_PROPERTIES_FINALLY = 'GET_MY_PROPERTIES_FINALLY';

//Update My Property
export const UPDATE_MY_PROPERTY_REQUEST = 'UPDATE_MY_PROPERTY_REQUEST';
export const UPDATE_MY_PROPERTY_SUCCESS = 'UPDATE_MY_PROPERTY_SUCCESS';
export const UPDATE_MY_PROPERTY_FINALLY = 'UPDATE_MY_PROPERTY_FINALLY';

//Delete My Property
export const DELETE_MY_PROPERTY_REQUEST = 'DELETE_MY_PROPERTY_REQUEST';
export const DELETE_MY_PROPERTY_SUCCESS = 'DELETE_MY_PROPERTY_SUCCESS';
export const DELETE_MY_PROPERTY_FINALLY = 'DELETE_MY_PROPERTY_FINALLY';

//Get My Preference
export const GET_MY_PREFERENCE_REQUEST = 'GET_MY_PREFERENCE_REQUEST';
export const GET_MY_PREFERENCE_SUCCESS = 'GET_MY_PREFERENCE_SUCCESS';
export const GET_MY_PREFERENCE_FINALLY = 'GET_MY_PREFERENCE_FINALLY';

//Update My Preference
export const UPDATE_MY_PREFERENCE_REQUEST = 'UPDATE_MY_PREFERENCE_REQUEST';
export const UPDATE_MY_PREFERENCE_SUCCESS = 'UPDATE_MY_PREFERENCE_SUCCESS';
export const UPDATE_MY_PREFERENCE_FINALLY = 'UPDATE_MY_PREFERENCE_FINALLY';

//Create dream address
export const CREATE_DREAM_ADDRESS_REQUEST = 'CREATE_DREAM_ADDRESS_REQUEST';
export const CREATE_DREAM_ADDRESS_SUCCESS = 'CREATE_DREAM_ADDRESS_SUCCESS';
export const CREATE_DREAM_ADDRESS_FINALLY = 'CREATE_DREAM_ADDRESS_FINALLY';

//Get dream addresses
export const GET_DREAM_ADDRESSES_REQUEST = 'GET_DREAM_ADDRESSES_REQUEST';
export const GET_DREAM_ADDRESSES_SUCCESS = 'GET_DREAM_ADDRESSES_SUCCESS';
export const GET_DREAM_ADDRESSES_FINALLY = 'GET_DREAM_ADDRESSES_FINALLY';

//Delete dream address
export const DELETE_DREAM_ADDRESS_REQUEST = 'DELETE_DREAM_ADDRESS_REQUEST';
export const DELETE_DREAM_ADDRESS_SUCCESS = 'DELETE_DREAM_ADDRESS_SUCCESS';
export const DELETE_DREAM_ADDRESS_FINALLY = 'DELETE_DREAM_ADDRESS_FINALLY';

//Get Matched Properties
export const GET_MATCHED_PROPERTIES_REQUEST = 'GET_MATCHED_PROPERTIES_REQUEST';
export const GET_MATCHED_PROPERTIES_SUCCESS = 'GET_MATCHED_PROPERTIES_SUCCESS';
export const GET_MATCHED_PROPERTIES_FINALLY = 'GET_MATCHED_PROPERTIES_FINALLY';

//Get Support Closers
export const GET_TOP_SUPPORT_CLOSERS_REQUEST = 'GET_TOP_SUPPORT_CLOSERS_REQUEST';
export const GET_TOP_SUPPORT_CLOSERS_SUCCESS = 'GET_TOP_SUPPORT_CLOSERS_SUCCESS';
export const GET_TOP_SUPPORT_CLOSERS_FINALLY = 'GET_TOP_SUPPORT_CLOSERS_FINALLY';

//Types for Login
export const LOGIN_REQUEST_REQUEST = 'LOGIN_REQUEST_REQUEST';
export const LOGIN_REQUEST_SUCCESS = 'LOGIN_REQUEST_SUCCESS';
export const LOGIN_REQUEST_FAILURE = 'LOGIN_REQUEST_FAILURE';
//Types for Logout
export const LOGOUT_REQUEST_REQUEST = 'LOGOUT_REQUEST_REQUEST';
export const LOGOUT_REQUEST_SUCCESS = 'LOGOUT_REQUEST_SUCCESS';
export const LOGOUT_REQUEST_FAILURE = 'LOGOUT_REQUEST_FAILURE';
//Types for Social Login
export const SOCIAL_LOGIN_REQUEST = 'SOCIAL_LOGIN_REQUEST';
export const SOCIAL_LOGIN_REQUEST_SUCCESS = 'SOCIAL_LOGIN_REQUEST_SUCCESS';
export const SOCIAL_LOGIN_REQUEST_FAILURE = 'SOCIAL_LOGIN_REQUEST_FAILURE';
//Types for Sign up
export const SIGNUP_REQUEST = 'SIGNUP_REQUEST';
export const SIGNUP_SUCCESS = 'SIGNUP_SUCCESS';
export const SIGNUP_FAILURE = 'SIGNUP_FAILURE';

//Types for Create Support Closure
export const SET_SUPPORT_INFO_REQUEST = 'SET_SUPPORT_INFO_REQUEST';
export const SET_SUPPORT_INFO_SUCCESS = 'SET_SUPPORT_INFO_SUCCESS';

export const ADD_SUPPORT_INFO_REQUEST = 'ADD_SUPPORT_INFO_REQUEST';
export const ADD_SUPPORT_INFO_SUCCESS = 'ADD_SUPPORT_INFO_SUCCESS';
export const ADD_SUPPORT_INFO_FAILURE = 'ADD_SUPPORT_INFO_FAILURE';

//Types for OTP Verification
export const OTP_VERIFY_REQUEST = 'OTP_VERIFY_REQUEST';
export const OTP_VERIFY_SUCCESS = 'OTP_VERIFY_SUCCESS';
export const OTP_VERIFY_FAILURE = 'OTP_VERIFY_FAILURE';

//Types for  forgot password
export const FORGOT_PASSWORD_REQUEST = 'FORGOT_PASSWORD_REQUEST';
export const FORGOT_PASSWORD_SUCCESS = 'FORGOT_PASSWORD_SUCCESS';
export const FORGOT_PASSWORD_FAILURE = 'FORGOT_PASSWORD_FAILURE';

//Types for reset password
export const RESET_PASSWORD_REQUEST = 'RESET_PASSWORD_REQUEST';
export const RESET_PASSWORD_SUCCESS = 'RESET_PASSWORD_SUCCESS';
export const RESET_PASSWORD_FAILURE = 'RESET_PASSWORD_FAILURE';

//Types for User Type
export const USER_TYPE_REQUEST = 'USER_TYPE_REQUEST';
export const USER_TYPE_SUCCESS = 'USER_TYPE_SUCCESS';
export const USER_TYPE_FAILURE = 'USER_TYPE_FAILURE';

//Types for  Resend OTP
export const RESEND_OTP_REQUEST = 'RESEND_OTP_REQUEST';
export const RESEND_OTP_SUCCESS = 'RESEND_OTP_SUCCESS';
export const RESEND_OTP_FAILURE = 'RESEND_OTP_FAILURE';

//Types for  Add Additional Info
export const ADD_ADDITIONAL_INFO_REQUEST = 'ADD_ADDITIONAL_INFO_REQUEST';
export const ADD_ADDITIONAL_INFO_SUCCESS = 'ADD_ADDITIONAL_INFO_SUCCESS';
export const ADD_ADDITIONAL_INFO_FAILURE = 'ADD_ADDITIONAL_INFO_FAILURE';

//Types for Chats

//Get All Chats
export const GET_ALL_CHATS_REQUEST = 'GET_ALL_CHATS_REQUEST';
export const GET_ALL_CHATS_SUCCESS = 'GET_ALL_CHATS_SUCCESS';

//Delete Chat
export const DELETE_CHAT_REQUEST = 'DELETE_CHAT_REQUEST';
export const DELETE_CHAT_SUCCESS = 'DELETE_CHAT_SUCCESS';
export const DELETE_CHAT_FINALLY = 'DELETE_CHAT_FINALLY';

//Read Chat Messages
export const READ_CHAT_MESSAGES_REQUEST = 'READ_CHAT_MESSAGES_REQUEST';
export const READ_CHAT_MESSAGES_SUCCESS = 'READ_CHAT_MESSAGES_SUCCESS';

export const SET_CONVERSATION_OPENED_ID = 'SET_CONVERSATION_OPENED_ID';

//Types for Notifications

//Get All Notifications
export const GET_ALL_NOTIFICATIONS_REQUEST = 'GET_ALL_NOTIFICATIONS_REQUEST';
export const GET_ALL_NOTIFICATIONS_SUCCESS = 'GET_ALL_NOTIFICATIONS_SUCCESS';
export const GET_ALL_NOTIFICATIONS_FINALLY = 'GET_ALL_NOTIFICATIONS_FINALLY';

//Notification seen
export const NOTIFICATION_SEEN = 'NOTIFICATION_SEEN';

//Add Notification
export const ADD_NOTIFICATION = 'ADD_NOTIFICATION';

//Types for Settings

// get profile info req
export const GET_PROFILE_REQUEST = 'GET_PROFILE_REQUEST';
export const GET_PROFILE_SUCCESS = 'GET_PROFILE_SUCCESS';
export const GET_PROFILE_FAILURE = 'GET_PROFILE_FAILURE';

// update profile info req
export const UPDATE_PROFILE_REQUEST = 'UPDATE_PROFILE_REQUEST';
export const UPDATE_PROFILE_SUCCESS = 'UPDATE_PROFILE_SUCCESS';
export const UPDATE_PROFILE_FAILURE = 'UPDATE_PROFILE_FAILURE';

//Get CARD LIST
export const GET_CARD_LIST_REQUEST = 'GET_CARD_LIST_REQUEST';
export const GET_CARD_LIST_SUCCESS = 'GET_CARD_LIST_SUCCESS';
export const GET_CARD_LIST_FAILURE = 'GET_CARD_LIST_FAILURE';

//Add Default Card
export const ADD_DEFAULT_CARD_REQUEST = 'ADD_DEFAULT_CARD_REQUEST';
export const ADD_DEFAULT_CARD_SUCCESS = 'ADD_DEFAULT_CARD_SUCCESS';
export const ADD_DEFAULT_CARD_FAILURE = 'ADD_DEFAULT_CARD_FAILURE';

//Get Default Card
export const GET_DEFAULT_CARD_REQUEST = 'GET_DEFAULT_CARD_REQUEST';
export const GET_DEFAULT_CARD_SUCCESS = 'GET_DEFAULT_CARD_SUCCESS';
export const GET_DEFAULT_CARD_FAILURE = 'GET_DEFAULT_CARD_FAILURE';

//ADD CARD
export const ADD_CARD_REQUEST = 'ADD_CARD_REQUEST';
export const ADD_CARD_SUCCESS = 'ADD_CARD_SUCCESS';
export const ADD_CARD_FAILURE = 'ADD_CARD_FAILURE';
//Deleted Card
export const DELETE_CARD_REQUEST = 'DELETE_CARD_REQUEST';
export const DELETE_CARD_SUCCESS = 'DELETE_CARD_SUCCESS';
export const DELETE_CARD_FAILURE = 'DELETE_CARD_FAILURE';
//Edit card
export const EDIT_CARD_REQUEST = 'EDIT_CARD_REQUEST';
export const EDIT_CARD_SUCCESS = 'EDIT_CARD_SUCCESS';
export const EDIT_CARD_FAILURE = 'EDIT_CARD_FAILURE';
//Pay With Debit
export const PAY_WITH_DEBIT_REQUEST = 'PAY_WITH_DEBIT_REQUEST';
export const PAY_WITH_DEBIT_SUCCESS = 'PAY_WITH_DEBIT_SUCCESS';
export const PAY_WITH_DEBIT_FAILURE = 'PAY_WITH_DEBIT_FAILURE';

//Pay With Google
export const PAY_WITH_SOCIAL_REQUEST = 'PAY_WITH_SOCIAL_REQUEST';
export const PAY_WITH_SOCIAL_SUCCESS = 'PAY_WITH_SOCIAL_SUCCESS';
export const PAY_WITH_SOCIAL_FAILURE = 'PAY_WITH_SOCIAL_FAILURE';

export const SET_IN_APP_NOTIFICATION_TO_SHOW = 'SET_IN_APP_NOTIFICATION_TO_SHOW';

export const SET_USER_LOCATION_REQUEST = 'SET_USER_LOCATION_REQUEST';
export const SET_USER_LOCATION_SUCCESS = 'SET_USER_LOCATION_SUCCESS';
