import {svgIcons} from '../../assets/svgs/index';

export const appLogos = {
  appLogo: require('../../assets/logos/app_logo.png'),
  roundLogo: require('../../assets/logos/round_logo.png'),
  supportLogo: require('../../assets/logos/support_logo.png'),
};

export const appImages = {
  slider1: require('../../assets/images/slider1.png'),
  slider2: require('../../assets/images/slider2.png'),
  slider3: require('../../assets/images/slider3.png'),
  homeImg: require('../../assets/images/home_img.png'),
  personPh: require('../../assets/images/person_ph.png'),
  personPh1: require('../../assets/images/person_ph1.png'),
  personImg: require('../../assets/images/person_img.png'),
  map: require('../../assets/images/map.png'),
  home1: require('../../assets/images/home1.png'),
  home2: require('../../assets/images/home2.png'),
  home3: require('../../assets/images/home3.png'),
  home4: require('../../assets/images/home4.png'),
  home5: require('../../assets/images/home5.png'),
  home6: require('../../assets/images/home6.png'),
  person1: require('../../assets/images/person1.png'),
  person2: require('../../assets/images/person2.png'),
  person3: require('../../assets/images/person3.png'),
  cardBg: require('../../assets/images/card_bg.png'),
  avatar: require('../../assets/images/avatar.png'),
  boost: require('../../assets/images/boost.png'),
  dummyProfile: require('../../assets/images/dummy-profile.png'),
};

export const appIcons = {
  box: require('../../assets/icons/box.png'),
  checkedBox: require('../../assets/icons/checked_box.png'),
  google: require('../../assets/icons/google.png'),
  apple: require('../../assets/icons/apple.png'),
  backArrow: require('../../assets/icons/back_arrow.png'),
  america: require('../../assets/icons/america.png'),
  gallery_1: require('../../assets/icons/gallery_1.png'),
  themeCamera: require('../../assets/icons/themeCamera.png'),
  gallery: require('../../assets/icons/gallery.png'),
  person: require('../../assets/icons/person.png'),
  bgPencil: require('../../assets/icons/bgPencil.png'),
  home: require('../../assets/icons/home.png'),
  contractor: require('../../assets/icons/contractor.png'),
  sellHome: require('../../assets/icons/sell_home.png'),
  buyHome: require('../../assets/icons/buy_home.png'),
  contractorHome: require('../../assets/icons/contractor_home.png'),
  homeIcon: require('../../assets/icons/home_icon.png'),
  bookmarksIcon: require('../../assets/icons/bookmarks_icon.png'),
  searchIcon: require('../../assets/icons/search_icon.png'),
  messageIcon: require('../../assets/icons/message_icon.png'),
  locIcon: require('../../assets/icons/loc_icon.png'),
  mapIcon: require('../../assets/icons/map_icon.png'),
  crossIcon: require('../../assets/icons/cross_icon.png'),
  starIcon: require('../../assets/icons/star_icon.png'),
  starWithLinesIcon: require('../../assets/icons/star_with_lines.png'),
  addressIcon: require('../../assets/icons/address_icon.png'),
  infoIcon: require('../../assets/icons/info_icon.png'),
  cross: require('../../assets/icons/cross.png'),
  bedIcon: require('../../assets/icons/bed_icon.png'),
  bathIcon: require('../../assets/icons/bath_icon.png'),
  heartIcon: require('../../assets/icons/heart_icon.png'),
  blueHome: require('../../assets/icons/blue_home.png'),
  modelHome: require('../../assets/icons/model_home.png'),
  vacant: require('../../assets/icons/vacant.png'),
  all: require('../../assets/icons/all.png'),
  editIcon: require('../../assets/icons/edit_icon.png'),
  delIcon: require('../../assets/icons/del_icon.png'),
  markedIcon: require('../../assets/icons/marked_icon.png'),
  locMatch: require('../../assets/icons/loc_match.png'),
  homeMatch: require('../../assets/icons/home_match.png'),
  checkIcon: require('../../assets/icons/check_icon.png'),
  crossedIcon: require('../../assets/icons/crossed_icon.png'),
  galleryIcon: require('../../assets/icons/gallery_icon.png'),
  cameraIcon: require('../../assets/icons/camera_icon.png'),
  share: require('../../assets/icons/share.png'),
  notify: require('../../assets/icons/notify.png'),
  payMethod: require('../../assets/icons/pay_method.png'),
  privacy: require('../../assets/icons/privacy.png'),
  support: require('../../assets/icons/support.png'),
  terms: require('../../assets/icons/terms.png'),
  faq: require('../../assets/icons/faq.png'),
  blockedList: require('../../assets/icons/blocked_list.png'),
  cards: require('../../assets/icons/cards.png'),
  googleWallet: require('../../assets/icons/google_wallet.png'),
  checked: require('../../assets/icons/checked.png'),
  unchecked: require('../../assets/icons/unchecked.png'),
  visa: require('../../assets/icons/visa.png'),
  delete: require('../../assets/icons/delete.png'),
  edit: require('../../assets/icons/edit.png'),
  default: require('../../assets/icons/default.png'),
  visa: require('../../assets/icons/visa.png'),
  masterCard: require('../../assets/icons/masterCard.png'),

  //Home Icons
  type: require('../../assets/icons/Type.png'),
  ownership: require('../../assets/icons/ownership.png'),
  garage: require('../../assets/icons/Garages.png'),
  exterior: require('../../assets/icons/Exterior.png'),
  balcony: require('../../assets/icons/balcony.png'),
  exposure: require('../../assets/icons/Exposure.png'),
  security: require('../../assets/icons/Security.png'),
  pets: require('../../assets/icons/Pets.png'),
  utilities: require('../../assets/icons/Utilites.png'),
  water: require('../../assets/icons/Water.png'),
  sware: require('../../assets/icons/Sewer.png'),
  source: require('../../assets/icons/Source.png'),
  heat: require('../../assets/icons/Heat.png'),
  airCon: require('../../assets/icons/Condition.png'),
  loundry: require('../../assets/icons/Loundary.png'),
  fire: require('../../assets/icons/Fire.png'),
  vacume: require('../../assets/icons/Vaccum.png'),
  bassement: require('../../assets/icons/Base.png'),
  pool: require('../../assets/icons/Pool.png'),
  bath: require('../../assets/icons/Bath.png'),
  bed: require('../../assets/icons/Bed.png'),
  living_space: require('../../assets/icons/Living.png'),
  kitchen: require('../../assets/icons/kitchen.png'),
  parking: require('../../assets/icons/Parking.png'),
  garage_space: require('../../assets/icons/Garage.png'),
  driveway: require('../../assets/icons/driveway.png'),
  HouseType: require('../../assets/icons/HouseType.png'),
  HouseStyle: require('../../assets/icons/HouseStyle.png'),
  parkingType: require('../../assets/icons/parkingType.png'),
  priceTag: require('../../assets/icons/priceTag.png'),
  built: require('../../assets/icons/built.png'),
  condoType: require('../../assets/icons/condoType.png'),
  condoStyle: require('../../assets/icons/condoStyle.png'),
  settings: require('../../assets/icons/settings.png'),
  pdf: require('../../assets/icons/pdf.png'),
  property: require('../../assets/icons/property.png'),
  support_closer: require('../../assets/icons/support_closer.png'),
  chat: require('../../assets/icons/chat.png'),
  phone: require('../../assets/icons/phone.png'),

  //map screen
  circle:require('../../assets/icons/circle.png'),
  polygon:require('../../assets/icons/polygon.png'),
  plus:require('../../assets/icons/plus.png'),
  minus:require('../../assets/icons/minus.png'),
  navigator:require('../../assets/icons/navigator.png'),
  refresh:require('../../assets/icons/refresh.png'),
  handHold:require('../../assets/icons/handHold.png'),
  handDrag:require('../../assets/icons/handDrag.png'),
  propertyMarker:require('../../assets/icons/property-marker.png'),
};

export const appSvgs = {
  ...svgIcons,
};
